name: Copy File to Another Repo

on:
  push:
    branches:
      - main # Trigger the workflow on commits to the main branch

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3

    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        repository: target-owner/target-repo
        token: ${{ secrets.TARGET_REPO_PAT }}
        path: target-repo

    - name: Copy file
      run: |
        cp one-column.pdf personal-website/public/assets/resume.pdf

    - name: Commit changes
      run: |
        cd target-repo
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add public/assets/resume.pdf
        git commit -m 'Copy resume from source repo on commit'

    - name: Push changes
      run: |
        cd target-repo
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
